name: doomsms
description: "Découvrez DoomSMS, une application de messagerie mobile sécurisée qui vous offre une communication privée et chiffrée de bout en bout, le tout en peer-to-peer."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  crypto: ^3.0.0
  shared_preferences: ^2.0.0
  pointycastle: ^4.0.0
  network_info_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
